// --- DOM Elements ---
const authSection = document.getElementById('auth-section');
const uploadSection = document.getElementById('upload-section');
const resultSection = document.getElementById('result-section');
const loadingOverlay = document.getElementById('loading-overlay');
const signInForm = document.getElementById('sign-in-form');
const uploadForm = document.getElementById('upload-form');
const imageInput = document.getElementById('image-input');
const previewContainer = document.getElementById('preview-container');
const storyContent = document.getElementById('story-content');
const downloadButton = document.getElementById('download-button');

// --- State ---
let isAuthenticated = false;

// --- Helper Functions ---

/**
 * Simulates a successful sign-in and switches the view.
 */
signInForm.addEventListener('submit', (e) => {
    e.preventDefault();
    // Assuming success for the frontend demo:
    isAuthenticated = true;
    authSection.classList.add('hidden');
    uploadSection.classList.remove('hidden');
    console.log('User signed in successfully.');
});

/**
 * Handles image file selection and shows previews.
 */
imageInput.addEventListener('change', (e) => {
    previewContainer.innerHTML = '';
    const files = e.target.files;
    
    if (files.length > 5) {
        alert('You can only upload a maximum of 5 images.');
        imageInput.value = ''; // Clear selection
        return;
    }

    Array.from(files).forEach(file => {
        const reader = new FileReader();
        reader.onload = (e) => {
            const img = document.createElement('img');
            img.src = e.target.result;
            previewContainer.appendChild(img);
        };
        reader.readAsDataURL(file);
    });
});

/**
 * Handles the story generation submission.
 */
uploadForm.addEventListener('submit', async (e) => {
    e.preventDefault();
    
    if (!isAuthenticated) {
        alert('Please sign in first.');
        return;
    }

    // Show loading state and hide upload form
    uploadSection.classList.add('hidden');
    loadingOverlay.classList.remove('hidden');

    const files = imageInput.files;
    const emotion = document.getElementById('emotion-select').value;
    
    console.log(`Starting generation for ${files.length} images with emotion: ${emotion}`);

    // --- Core AI/Backend Logic Placeholder ---
    try {
        // Simulating the backend response and delay
        await new Promise(resolve => setTimeout(resolve, 4000)); 
        
        // **NOTE:** You must replace 'placeholder_audio.mp3' with a real audio file 
        // URL generated by your Text-to-Speech service.
        const storyText = `The ancient stone walls, bathed in the soft glow of the setting sun, seemed to whisper tales of a forgotten era. A lone bird flew across the vast, azure sky, its silhouette a perfect symbol of freedom. This journey, filled with anticipation and a quiet sense of destiny, brought a wave of pure, ${emotion} happiness to the traveler's heart. Every picture holds a moment of this extraordinary joy, now captured in a story just for you.`;
        const audioUrl = 'placeholder_audio.mp3'; 

        displayStoryResult(storyText, audioUrl);

    } catch (error) {
        console.error('Error during story generation:', error);
        alert('An error occurred while generating the story.');
        // Go back to upload page
        uploadSection.classList.remove('hidden');
    } finally {
        loadingOverlay.classList.add('hidden');
    }
});

/**
 * Renders the story result page.
 * @param {string} text - The generated story text.
 * @param {string} audioSrc - URL of the generated audio file.
 */
function displayStoryResult(text, audioSrc) {
    storyContent.innerHTML = `
        <h3>Generated Story Text:</h3>
        <p id="story-text">${text}</p>
        <h3>Listen:</h3>
        <audio controls src="${audioSrc}">
            Your browser does not support the audio element.
        </audio>
    `;
    
    // Set up download button
    downloadButton.onclick = () => {
        // This simulates a download by creating a temporary link element.
        const a = document.createElement('a');
        a.href = audioSrc;
        a.download = `AI_Story_${new Date().getTime()}.mp3`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        alert('Download triggered (Note: The audio file is a placeholder).');
    };
    
    resultSection.classList.remove('hidden');
    downloadButton.classList.remove('hidden');
}

// Initial state: ensure only sign-in is visible
document.addEventListener('DOMContentLoaded', () => {
    authSection.classList.remove('hidden');
    uploadSection.classList.add('hidden');
    resultSection.classList.add('hidden');
});